### ISSUE TITLE
SNMP::Manager get => raw octet-string

### ISSUE THREAD

**Issue by takz1977** [hallidave/ruby-snmp#13]
Hi,
in my case,I'm use manager.get("some oid for return a octet-string")
got result is ValueDecoderMap.

look like decode to integer. but my octet-string have mix of some integer and ascii.

`so, how I get just raw octet-string?`

ps. 
- raw result look like the result from snmpget() php function.
- or any way to rewrite ValueDecoderMap in my rule?

takz.

**Comment by hallidave** [comment]
Closing old issues
