### ISSUE TITLE
Error handling if the OID does not exist?

### ISSUE THREAD

**Issue by scottharman** [hallidave/ruby-snmp#24]
Hi guys
I want to add some error handling to my code - I'm only looking for specific OIDs so if they aren't present, either the application isn't running, or it isn't installed - What's the best way to test for this, and prevent my code from spazzing out?
At the moment I just get a fatal timeout when issuing a get or a get-next, which isn't ideal. I'd rather just break or exit cleanly.

**Comment by bjmllr** [comment]
Have you tried `rescue SNMP::RequestTimeout`?
