### ISSUE TITLE
Broadcast get support

### ISSUE THREAD

**Issue by ressu** [hallidave/ruby-snmp#27]
In discovery situations, it's quite common to make a broadcast request to find which devices are available in the network. At the moment ruby-snmp doesn't support it.

As far as I can see, three things need to happen for discovery to be possible with ruby-snmp. VarBind objects need to have an origin field, which contains the IP address of the reply, new transport needs to be created (based on UDPTransport) which sets SO_BROADCAST socket option and finally get needs to be updated to allow multiple replies.

**Comment by xanview** [comment]
Any update on this? :)
