### ISSUE TITLE
bulk_get with >33 rows 

### ISSUE THREAD

**Issue by ytti** [hallidave/ruby-snmp#30]
# pry -r snmp

[1] pry(main)> s=SNMP::Manager.new(:Host=>'10.20.1.86', :Community=>'public')
[2] pry(main)> s.get_bulk(0, 34, '1.0.8802.1.1.2.1.1.7.1.1.1.4.5.79.68.188')
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
/var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:491: warning: nil
SNMP::RequestTimeout: host 10.20.1.86 not responding
from /var/lib/gems/1.9.1/gems/snmp-1.1.1/lib/snmp/manager.rb:282:in `get_bulk'
[3] pry(main)> s.get_bulk(0, 33, '1.0.8802.1.1.2.1.1.7.1.1.1.4.5.79.68.188')
=> #<SNMP::Response:0x9e1fb50
 @error_index=0,
 @error_status=0,
....
....

Completely reproducible, not sure what is going on. From CLI snmpbulkget with -Cr 34 works great.

snmp (1.1.1)
ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]
# snmpbulkwalk 10.20.1.86 iso.3.6.1.2.1.1.1.0

iso.3.6.1.2.1.1.1.0 = STRING: "Arista Networks EOS version 4.12.5.1 running on an Arista Networks DCS-7508"

**Comment by hallidave** [comment]
Closing old issues
