### ISSUE TITLE
"OIDs are not increasing"  error processing should be configurable

### ISSUE THREAD

**Issue by xopnet** [hallidave/ruby-snmp#31]
Many network switches do not return a list of OIDs in ascending order.  When we
use ruby-snmp for these devices, processing is aborted.

We cannot go to every device maker and get them to change their SNMP agents.
Also, note that snmpwalk has an option to ignore out-of-order OIDs.

Can you make this "OIDs are not increasing"  logic configurable to allow us to ignore
out-of-order OIDs?

**Comment by hallidave** [comment]
This option has now been added. Thanks to @bjmllr for the patch.
