### ISSUE TITLE
Ruby 2.2 Comparison Operator Deprecation Warning

### ISSUE THREAD

**Issue by urma** [hallidave/ruby-snmp#35]
The following piece of code has been running in an application which survived transitioning from Ruby 1.9 to 2.0, 2.1 and now 2.2.

```
# SNMP has a mechanism for letting us know if we've hit the end of
# a walk. If that's true, then we'll return
if last_value == SNMP::EndOfMibView
  return
end
```

After the upgrade to Ruby 2.2, however, I started observing the following warnings in our logs:

```
/path/to/protocol.rb:448: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/path/to/protocol.rb:448: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

This seems to be related to this Ruby change, which made it to Ruby 2.2 -- https://bugs.ruby-lang.org/issues/7688. Other projects have been affected as well (I found a nice drill down on this on https://github.com/RubyMoney/money/issues/469).

I can avoid the warning if we use `if last_value.is_a?(SNMP::EndOfMibView)` instead of the previous idiom, but a proper 2.2-compatible update to `snmp` would be more desirable. I tried digging down the source code to submit a pull request, but it's not clear to me what exactly would need to be touched.

**Comment by hallidave** [comment]
Fixed in 1.3.0.
