### ISSUE TITLE
get_bulk with non_repeaters greater than 18

### ISSUE THREAD

**Issue by genelatham** [hallidave/ruby-snmp#36]
SNMP version 1.2.0
If get_bulk is called with a non_repeaters parameter greater than 18 it fails with 
pdu.rb:181:in `error_status=': 19 (SNMP::InvalidErrorStatus)

get_bulk calls GetBulkRequest.new with the non_repeaters count in the error_status parameter.  When PDU.initialize tries to assign it to self.error_status the error_status= routine tries to decode it and since it is our of range (max valid error_status is 18) it throws the exception.

**Comment by hallidave** [comment]
Fixed. Too late for you, but thanks anyways for reporting.
