### ISSUE TITLE
Support for AgentX

### ISSUE THREAD

**Issue by maxmeyer** [hallidave/ruby-snmp#37]
Hi, does `ruby-snmp` support [`AgentX`](https://www.ietf.org/rfc/rfc2741.txt)? 

I think about writing a small daemon using `dbus` + `agentx` to monitor `systemd`-services. Something similar to https://github.com/joonty/systemd_mon.

**Comment by hallidave** [comment]
No. There is no support for AgentX. It's not really intended for building agents.
