### ISSUE TITLE
Ability to access name?

### ISSUE THREAD

**Issue by xanview** [hallidave/ruby-snmp#39]
For example: 

```ruby
def test
  manager.walk(['test']) do |row|
    row.each {|vb| return vb}
  end
end

vb = test()
```

Now I'm able to run to_s and see the name there, so far so good:

```ruby
[6] pry(main)> vb.to_s
=> "[name=TEST-COMMON-MIB::testGeneralIndex.3, value=3 (INTEGER)]"
[7] pry(main)> 
```

Great, now I want to get just the name, or "TEST-COMMON-MIB::testGeneralIndex.3":

```ruby
[7] pry(main)> vb.name
=> [1, 3, 6, 1, 4, 1, 6548, 2, 1, 1, 1, 1, 3]
```

But it returns the "oid" representation, not the string name as above :( -- Any way to get the name?

**Comment by hallidave** [comment]
IRB calls the 'inspect' method. Try 'to_s' instead (i.e. vb.name.to_s).

**Comment by xanview** [comment]
Ah, thank you, that works!
