### ISSUE TITLE
Patch to add IpAddressV6 to varbind

### ISSUE THREAD

**Issue by jcfoster** [hallidave/ruby-snmp#43]
Attached is a diff patch that uses some code from IPAddr to add the IpAddressV6 to varbind.  You are welcome to use this code as you please.  

Jeff F>
[varbind-IpAddressV6.zip](https://github.com/hallidave/ruby-snmp/files/423660/varbind-IpAddressV6.zip)

**Comment by hallidave** [comment]
Could you provide a pull request instead?
