### ISSUE TITLE
Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by MattiL** [hallidave/ruby-snmp#47]
I got the following error in Logstash SNMP output plugin:
> {:error=>#<Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8>, :backtrace=>["org/jruby/RubyString.java:2630:in `concat'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/ber.rb:305:in `encode_tlv'", 
> "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/ber.rb:313:in `encode_octet_string'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/varbind.rb:140:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/varbind.rb:612:in `encode'",
>  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/varbind.rb:67:in `encode'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/varbind.rb:66:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/pdu.rb:194:in `encode_pdu'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/pdu.rb:260:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/pdu.rb:123:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:519:in `send_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:366:in `trap_v2'", "/usr/share/logstash/vendor/local_gems/7292f880/logstash-output-snmptrap-0.9.3/lib/logstash/outputs/snmptrap.rb:64:in `register'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:218:in `open'"

**Comment by MattiL** [comment]
I attach a patch that fixes the bug.

[encode_octet_string.txt](https://github.com/hallidave/ruby-snmp/files/1046862/encode_octet_string.txt)

**Comment by hallidave** [comment]
UTF-8 is not the default encoding for Ruby 1.9. Is the Logstash plugin or some other code changing the default encoding of Strings?

Forcing the encoding in the SNMP library is a bad idea. I think you will end up encoding the wrong OctetString length in some cases with the code that you've written.
