### ISSUE TITLE
Changing the TTL value

### ISSUE THREAD

**Issue by vardyb** [hallidave/ruby-snmp#50]
I am using ruby-snmp to send traps however we are experiencing issues passing through firewalls, the vendor have recommended that we try to increase the initial TTL on the host originating the traffic to 'TTL > 30'.  Is it possible to change the TTL setting used by ruby-snmp?

**Comment by hallidave** [comment]
You can create a custom transport class and set the TTL in there.

class MyTransport < SNMP::UDPTransport
  def initialize
    super
    @socket.setsockopt(Socket::IPPROTO_IP, Socket::IP_TTL, 64)
  end
end

snmp = SNMP::Manager.new(transport: MyTransport)

**Comment by vardyb** [comment]
@hallidave many thanks for the swift response, much appreciated.
