### ISSUE TITLE
Comparing with SNMP::Integer is inconsistent and might produce an error

### ISSUE THREAD

**Issue by grasshopper1** [hallidave/ruby-snmp#53]
When a object is compared with SNMP::Integer to_i is called on this object, which doesn't seem like correct behaviour.

For example:

When comparing a SNMP::Integer object with SNMP::NoSuchInstance on the right side an error is produced and when comparing a SNMP::Integer object with SNMP::NoSuchInstance on the left side the expected result false is returned.

See proof in rails console:
```
> irb(main):043:0> r = snmp_manager.get_value('IF-MIB::ifIndex.43')
> => #<SNMP::Integer:0x39c4f5c @value=43>
> irb(main):044:0> r == SNMP::NoSuchInstance
> NoMethodError: undefined method `to_i' for SNMP::NoSuchInstance:Class
> irb(main):045:0> SNMP::NoSuchInstance == r
> => false
```
This is seen in snmp version 1.2.0

**Comment by hallidave** [comment]
Thanks for the bug report. This has been a problem since Ruby 2.3.0 when the behavior of Comparable#== changed. Fixed now. Released version 1.3.0 gem.
