### ISSUE TITLE
Suggestion to make Manager load_module consistent with MIB load_module

### ISSUE THREAD

**Issue by jcfoster** [hallidave/ruby-snmp#55]
To make Manager load_module more flexible and consistent with MIB load_module, I suggest the following change, this will not impact current code 

change -
   def load_module(name)
      @mib.load_module(name)
   end
to -
   def load_module(name, mib_dir=MIB::DEFAULT_MIB_PATH)
      @mib.load_module(name, mib_dir)
   end

**Comment by hallidave** [comment]
I think it's a good idea to allow the mib_dir to be specified for load_module (and load_modules), but for the Manager I think the mib_dir in the manager config is a better default than MIB::DEFAULT_MIB_PATH.
