### ISSUE TITLE
Request to support `disableAuthorization yes`

### ISSUE THREAD

**Issue by cleeland** [hallidave/ruby-snmp#56]
`snmptrapd` from net-snmp offers a configuration option wherein traps are not checked for any authorization information, thereby enabling reception and processing of *all* traps.  It appears that this option is not supported by ruby-snmp.

**Comment by hallidave** [comment]
Accepting all traps is the default behavior. If you want to check for community strings then you can set the "community" option in the TrapListener. Version 3 traps (and authorization) are not supported.

**Comment by cleeland** [comment]
Then my problem must lie with the logstash snmptrap input plugin.  Thanks.

**Comment by hallidave** [comment]
Looks like logstash changes the default to "public". Not sure if the
logstash validation will allow you to pass in nil or not.

https://github.com/logstash-plugins/logstash-input-snmptrap/blob/master/lib/logstash/inputs/snmptrap.rb#L29

**Comment by cleeland** [comment]
I filed a bug against logstash.  I also tried setting the community to `nil` as you suggest, e.g., 
```
snmptrap {
  community => nil
  ...
}
```
and the community gets set to `["nil"]`.  I suspect that logstash cannot fathom a world without community.
