### ISSUE TITLE
the decode_tlv() method fail to decode a hex string

### ISSUE THREAD

**Issue by Sassanid** [hallidave/ruby-snmp#60]
I configured an snmp trap with: snmptrap -c public -v 2c 127.0.0.1:1062 ""  1.3.6.1.4.1.5815.1.7.1.2.1.2 1.3.6.1.4.1.5815.1.7.1.2.1.2 x "07 e4 0a 0e 12 09 21 00 2b 00 00"

so the data type for "07 e4 0a 0e 12 09 21 00 2b 00 00" is hex string and  is decoded to something like: \\a\\xE4\\n\\x0E\\x12\\t!\\x00+\\x00\\x00\.. could anyone help on this?

**Comment by hallidave** [comment]
That's the default Ruby string representation for the hex values. If you want to print it in the same format as your input, you need to do something like this:

```ruby
"\a\xE4\n\x0E\x12\t!\x00+\x00\x00".b.unpack("C*").map { |c| "%02x" % c }.join(" ")
=> "07 e4 0a 0e 12 09 21 00 2b 00 00"
```

You could even add a custom formatting method, if you'd like.

```ruby
require 'snmp'

module SNMP
   class OctetString
     def to_hex_s
       self.unpack("C*").map { |c| "%02x" % c }.join(" ")
     end
   end
 end

s = SNMP::OctetString.new("\x07\xe4\x0a\x0e\x12\x09\x21\x00\x2b\x00\x00")
s.to_hex_s
=> "07 e4 0a 0e 12 09 21 00 2b 00 00"
```
